apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fnrg9s1hc-python
  janus-idp.io/tekton: fnrg9s1hc-python
  backstage.io/kubernetes-id: fnrg9s1hc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fnrg9s1hc-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
