apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fnrg9s1hc-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fnrg9s1hc-python 
  name: fnrg9s1hc-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fnrg9s1hc-python 
